blog/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_view
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [

]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.createUser, name='register'),
    path('login/', authentication_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilePage, name='profile'),
 )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #food/
    path('', views.IndexClassView.as_view(), name='index'),
    #food/1
    path('<int:pk>/',views.DetailClassView.as_view(), name='detail'),
    path('item/', views.item, name='item'),
    path('create-item', views.create_item, name='create_item'),
    path('update/<int:id>', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.Item_name

    Item_name = models.CharField(max_length=200)
    Item_desc = models.CharField(max_length=200)
    Item_price = models.IntegerField()
    Item_avalablity = models.BooleanField(default=True)
    Item_image = models.CharField(max_length=500, default="https://www.melbournefoodandwine.com.au/image-tools.php?w=560&h=440&src=/recipes/recipe-placeholder.jpg")
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='pictures/profilepic.jpg',upload_to='profile_prictures')
    location = models.CharField(max_length=100)


    def __str__(self):
        return self.user.username
    

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['Item_name', 'Item_price', 'Item_desc' , 'Item_image' , 'Item_avalablity']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class userCreation(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.translation import gettext as _
from django.core.paginator import Paginator
# Create your views here.
from django.db.models import Q

# def index(request):
#     context = {
#         'item_list': Item.objects.all()
#     }
#     return render(request, 'food/index.html', context)
order = '-date_posted'

class IndexClassView(ListView):
    model = Item
    template_name= 'food/index.html'
    context_object_name = 'item_list'
    
    paginate_by = 2
    
    def get_queryset(self):
        search_query = self.request.GET.get('foodsearch')
        if search_query:
            return Item.objects.filter(Item_name__icontains=search_query)
        return Item.objects.all()

def item(request):
    out = _('<h1>This is a view</h1>')
    return HttpResponse(out)


class DetailClassView(DetailView):
    model = Item
    template_name = 'food/detail.html'

# def detail(request, item_id):
#     context = {
#         'item': Item.objects.get(pk=item_id)
#     }
#     return render(request, 'food/detail.html', context)


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/create-item.html', {'form': form})


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/create-item.html', {'form': form, 'item': item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'food/delete-item.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import userCreation

# Create your views here.

def createUser(request):
    
    if request.method == 'POST':
        form = userCreation(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Your account {username} has succesfully created!")
            return redirect('food:index')
    else:
        form = userCreation()
    return render(request, 'users/createuser.html', { 'form':form } )


@login_required 
def profilePage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">SnappFood</a>
        
        <nav class="navbar">
            <a href="{% url 'food:create_item' %}" class="nav-link">Add Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-link">logout</a>
                <a href="{% url 'profile' %}" class="nav-link">Profile</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-link">Login</a>
                <a href="{% url 'register' %}" class="nav-link">Signup</a>                
            {% endif %}
            {% block extendnavbar %}
            {% endblock %}
        </nav>
        
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class=" alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html> 

food/templates/food/create-item.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

food/templates/food/delete-item.html
{% extends 'food/base.html' %}
{% load i18n %}
{% block body %}
    <form method="POST">
        {% trans "Are you sure you want to delete"%} {{ item.Item_name }}
        {% csrf_token %}
          <button type="submit"  method="POST">{% trans "Confirm" %}</button>
    </form>    
{% endblock %}

food/templates/food/detail.html
{%extends 'food/base.html' %}
{% load i18n %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card" src="{{ item.Item_image }}" height="300px"/>
        </div>
        <div class="col-md-6">
            <h1>{{ object.Item_name }}</h1>
            <h2>{{ object.Item_desc }}</h2>
            <h3>${{ object.Item_price }}</h3>
            <h3><a href="{% url 'food:delete_item' item.id %}">{% trans "delete" %}</a></h3>
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Document</title>
</head>
<body>
{% block extendnavbar %}
    <form class="form-inline" method="GET" action="" name="foodsearch">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
 {% endblock %} 
    {% block body %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
    <h6>{% trans "Your choosen language: " %} {{ LANGUAGE_CODE }}</h6>


    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" src="{{ item.Item_image }}" height="150px" width="150px">
            </div>
            <div class="col-md-4">
                <h3>{{ item.Item_name }}</h3>
                <h4>{{ item.Item_desc }}</h4>
                <h5>${{ item.Item_price }}</h5>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Detials</a>
            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
    {% endblock %}
    
</body>
</html>


<!-- <ul>
    <li>          
        <a href="{% url 'food:detail' item.id %}">{{item.pk}} -- {{item.Item_name}}</a>
    </li>
</ul> -->

users/templates/users/createuser.html
<form method='POST'>
    {% csrf_token %}
    {{ form }}
    <button type="submit" >Sing up</button>
</form>

users/templates/users/login.html
<form method="POST">
    {% csrf_token %} 
    {{ form }}
    <button type="submit" >login</button>
</form>

users/templates/users/logout.html
<h1>you have been logged out<h1>

users/templates/users/profile.html
<h1> welcome {{ user.username }}</h1>

<img width=800 src="{{ user.profile.image.url }}" >